### PR TITLE
Scope: Clarification

### PR DESCRIPTION
**Pull request by boucadair**

### CODE REVIEW

**Review by obonaventure — COMMENTED** [review]
The comment concerning TLS should not be misunderstood as indicating that TLS is not supported. I would remove it.

**Review by obonaventure — APPROVED** [review]

**Review by obonaventure — APPROVED** [review]

**Review by obonaventure — APPROVED** [review]

**Review by obonaventure — APPROVED** [review]

**Review by obonaventure — COMMENTED** [review]
What do you mean by "connections are not allowed between hosts of a domain" ?

**Comment by boucadair** [comment]
This is to control the hairpinning behavior.

I updated the text with a figure.


De : Olivier Bonaventure [mailto:notifications@github.com]
Envoyé : lundi 4 mars 2019 17:08
À : obonaventure/draft-tcp-converters
Cc : BOUCADAIR Mohamed TGI/OLN; Author
Objet : Re: [obonaventure/draft-tcp-converters] Scope: Clarification (#55)


@obonaventure commented on this pull request.

What do you mean by "connections are not allowed between hosts of a domain" ?

**Review by obonaventure — APPROVED** [review]
Then I understand. I suggest to replace the word domain by prefix.

**Pull request merged**
