### PR TITLE
Errors in the 0-31

### PR DESCRIPTION
**Pull request by boucadair**
These errors can be sent by the converter and the client (incoming connections). 

The OLD wording is correct.

### CODE REVIEW

**Review by obonaventure — CHANGES_REQUESTED** [review]
I disagree. This was a misunderstanding by Mirja. A Client sends a Convert message and the Converter replies with an Error message. I changed the text so that the Client does not send error messages. This was possible when the error was included in the RST, but is not possible anymore today.

**Comment by boucadair** [comment]
Still this is possible for incoming connections, not only RST.

**Comment by obonaventure** [comment]
In this case, I would not call the host that receives a SYN with the Convert TLV a Client. This is misleading

**Comment by boucadair** [comment]
What about the following: 

      This error code MUST be generated by a peer (e.g. Transport Converter) when it receives a request having a version number that it does not support.

      The value field MUST be set to the version supported by the
      peer.  When multiple versions are
      supported by the peer, it includes the
      list of supported version in the value field; each version is
      encoded in 8 bits.  The list of supported versions should be
      padded with zeros to end on a 32 bits boundary.

      Upon receipt of this error code, the remote peer (e.g., Client) checks whether it supports one of the versions returned
      by the peer.  The highest common
      supported version MUST be used by the remote peer in subsequent exchanges with the peer.

**Review by obonaventure — APPROVED** [review]
I'l update based on your new text

**Pull request merged**
