### PR TITLE
Align with with the submitted -09 version

### PR DESCRIPTION
**Pull request by boucadair**

### CODE REVIEW

**Comment by bhesmans** [comment]
Hello Med,

It seems that the build failed because you added the country only in the author list. : 
```
$ make
kramdown-rfc2629 draft-ietf-tcpm-converters.mkd > draft-ietf-tcpm-converters.xml
---
- No link definition for link ID 'this-rfc' found on line 74
xml2rfc draft-ietf-tcpm-converters.xml draft-ietf-tcpm-converters.txt
Parsing file draft-ietf-tcpm-converters.xml
ERROR: Unable to validate the XML document: draft-ietf-tcpm-converters.xml
 <string>: Line 26: Element postal content does not follow the DTD, expecting (street+ , (city | region | code | country)*), got (country)
Makefile:35: recipe for target 'draft-ietf-tcpm-converters.txt' failed
make: *** [draft-ietf-tcpm-converters.txt] Error 1
rm draft-ietf-tcpm-converters.xml`
```

If you want to add an address you need to specify street etc. Could you update your pull request ?

Thank you !

Benjamin

**Comment by boucadair** [comment]
Re-,

I thought those are optional (I’m used with xml).

I updated the pull request. Hope this is better now. Thanks.

Cheers,
Med

De : bhesmans [mailto:notifications@github.com]
Envoyé : lundi 22 juillet 2019 13:05
À : obonaventure/draft-tcp-converters
Cc : BOUCADAIR Mohamed TGI/OLN; Author
Objet : Re: [obonaventure/draft-tcp-converters] Align with with the submitted -09 version (#68)


Hello Med,

It seems that the build failed because you added the country only in the author list. :

$ make

kramdown-rfc2629 draft-ietf-tcpm-converters.mkd > draft-ietf-tcpm-converters.xml

---

- No link definition for link ID 'this-rfc' found on line 74

xml2rfc draft-ietf-tcpm-converters.xml draft-ietf-tcpm-converters.txt

Parsing file draft-ietf-tcpm-converters.xml

ERROR: Unable to validate the XML document: draft-ietf-tcpm-converters.xml

 <string>: Line 26: Element postal content does not follow the DTD, expecting (street+ , (city | region | code | country)*), got (country)

Makefile:35: recipe for target 'draft-ietf-tcpm-converters.txt' failed

make: *** [draft-ietf-tcpm-converters.txt] Error 1

rm draft-ietf-tcpm-converters.xml`

If you want to add an address you need to specify street etc. Could you update your pull request ?

Thank you !

Benjamin

**Comment by bhesmans** [comment]
It's seems that the build is still failing because it expects a street first. See [here](https://travis-ci.com/obonaventure/draft-tcp-converters/builds/120013448).

**Comment by boucadair** [comment]
I added an empty street… I was hoping that is possible to maintain some information private.


De : bhesmans [mailto:notifications@github.com]
Envoyé : lundi 22 juillet 2019 15:51
À : obonaventure/draft-tcp-converters
Cc : BOUCADAIR Mohamed TGI/OLN; Author
Objet : Re: [obonaventure/draft-tcp-converters] Align with with the submitted -09 version (#68)


It's seems that the build is still failing because it expects a street first. See here<https://travis-ci.com/obonaventure/draft-tcp-converters/builds/120013448>.

**Comment by bhesmans** [comment]
mmm The build system doesn't like empty street neither :-/ https://travis-ci.com/obonaventure/draft-tcp-converters/builds/120019489

**Comment by boucadair** [comment]
Updated + fixed some nits reported by Phil.

De : bhesmans [mailto:notifications@github.com]
Envoyé : lundi 22 juillet 2019 16:23
À : obonaventure/draft-tcp-converters
Cc : BOUCADAIR Mohamed TGI/OLN; Author
Objet : Re: [obonaventure/draft-tcp-converters] Align with with the submitted -09 version (#68)


mmm The build system doesn't like empty street neither :-/ https://travis-ci.com/obonaventure/draft-tcp-converters/builds/120019489

**Comment by obonaventure** [comment]
There are two remaining issues in the text :

No empty line between
~~~~~~~~~~~~~~~~~~~~~~~~~~~
{: #figtc title="A Transport Converter Relays Data between Pairs of TCP Connections"}

A title must start with # on first column and not a space before #

# Some Design Considerations {#sec-des}

Furthermore, there should be no tabulations

**Comment by obonaventure** [comment]
There are two remaining issues in the text :

No empty line between
~~~~~~~~~~~~~~~~~~~~~~~~~~~
{: #figtc title="A Transport Converter Relays Data between Pairs of TCP Connections"}

A title must start with # on first column and not a space before #

# Some Design Considerations {#sec-des}

Furthermore, there should be no tabulations

**Review by obonaventure — APPROVED** [review]

**Pull request merged**
